# Copyright (c) 2022-2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Check Licenses
description: Checks all licenses of a software project
inputs:
  generate-notice-file:
    description: Shall a notice file be output for all found licenses?
    default: true
  notice-file-name:
    description: Name of the generated markdown license report. File extension will be added by the action.
    default: NOTICE-GENERATED
  fail-on-violation:
    description: If true, fails the action if a non-whitelisted license is found. Defaults to true.
    default: true
  config-file-path:
    description: Path to the config file for the license checker.
    required: true
  github-token:
    description: GitHub token to overcome API rate limiting
    default: ${{ github.token }}
  generate-dash:
    description: Generate clearlydefined.input based on ClearDefined Scheme
    required: false
    default: false

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.generate-notice-file }}
    - ${{ inputs.notice-file-name }}
    - ${{ inputs.fail-on-violation }}
    - ${{ inputs.config-file-path }}
    - "--github-token"
    - ${{ inputs.github-token }}
    - ${{ inputs.generate-dash }}
