name: Create and Update Tags
on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: getVersions
        run: |
          semantic_version=$(python setup.py --version)
          major_version=$(cut -d '.' -f 1 <<< "$semantic_version")
          major_minor_version=$(cut -d '.' -f 1,2 <<< "$semantic_version")
          echo "semantic_version=v$semantic_version" >> $GITHUB_OUTPUT
          echo "major_version=v$major_version" >> $GITHUB_OUTPUT
          echo "major_minor_version=v$major_minor_version" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create_full_version"
        with:
          tag: ${{ steps.getVersions.outputs.semantic_version }}
          tag_exists_error: true
          force_push_tag: false
          message: "${{ steps.getVersions.outputs.semantic_version }}"

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create_major_minor"
        with:
          tag: ${{ steps.getVersions.outputs.major_minor_version }}
          tag_exists_error: false
          force_push_tag: true
          message: "${{ steps.getVersions.outputs.major_minor_version }}"

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create_major"
        with:
          tag: ${{ steps.getVersions.outputs.major_version }}
          tag_exists_error: false
          force_push_tag: true
          message: "${{ steps.getVersions.outputs.major_version }}"
