# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Update license notice file

on:
  workflow_dispatch:
  push:
    # Run only on branches/commits and not tags
    branches:
      - main

jobs:
  update_notice_file:
    runs-on: ubuntu-latest
    name: Check and update Licenses Notice file

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Clone License Check Repo
        uses: actions/checkout@v3
        with:
          repository: eclipse-velocitas/license-check
          ref: v1.1.0
          path: .github/actions/license-check

      - name: Run License Checker to update the notice file
        uses: ./.github/actions/license-check
        with:
          config-file-path: ./.licensechecker.yml
          fail-on-violation: false
          notice-file-name: "NOTICE-3RD-PARTY-CONTENT"
